USE Proyecto2;

DROP FUNCTION IF EXISTS SafeInput;
DELIMITER $$
CREATE FUNCTION SafeInput (input VARCHAR(1000)) RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    DECLARE IS_SAFE BOOLEAN DEFAULT FALSE;
    IF (input NOT REGEXP '[^A-Za-z0-9@.]') THEN
        SET IS_SAFE = TRUE;
    END IF;
    RETURN IS_SAFE;
END;
$$
DELIMITER ;